#!/usr/bin/python3

import paho.mqtt.client as mqtt
import time

client = mqtt.Client("test_pub_2")

client.connect("pi8.thenet", 1883, 60)

def onMessage(client, data, msg):
    distance = msg.payload

count = 0

while True:
  time.sleep(1)
  client.publish("hello/world", "count=" + str(count))
  count = count + 1

  client.publish("servo/1", str(count))